dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev
env:
  global:
    - DATABASE_BUSY_TIMEOUT=250
    - TEST_DATABASE_URL=/home/travis/lugh-test-database.sqlite
    - TEST_LUGH_BIND=localhost:3000
    - PATH="/home/travis/.cargo/bin:$PATH"
before_script:
  - cargo install diesel_cli --force
script:
  - make test
