language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev
env:
  global:
    - TEST_DATABASE_URL=/home/travis/lugh-test-database.sqlite
    - TEST_LUGH_BIND=localhost:3000
    - PATH="/home/travis/.cargo/bin:$PATH"
before_script:
  - cargo install diesel_cli
script:
  - make test
