[package]
name = "lugh"
version = "0.1.0"
authors = ["Raphaël Lustin <raphael@lustin.fr>"]

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel", features = ["sqlite"] }
diesel_codegen = { git = "https://github.com/diesel-rs/diesel", features = ["sqlite"] }
dotenv = "0.8.0"
iron = "*"
params = "0.5.0"
router = "*"
mount = "*"
rustc-serialize = "*"
staticfile = "*"
time = "0.1.35"

[dev-dependencies]
dotenv = "0.8.0"
hyper = "*"
rustc-serialize = "*"
