[package]
name = "lugh"
version = "0.1.0"
authors = ["Raphaël Lustin <raphael@lustin.fr>"]

[dependencies]
diesel = "0.8.0"
diesel_codegen = { version = "0.8.0", features = ["sqlite"] }
dotenv = "0.8.0"
iron = "*"
params = "0.5.0"
router = "*"
mount = "*"
rustc-serialize = "*"
staticfile = "*"
time = "0.1.35"

[dev-dependencies]
dotenv = "0.8.0"
hyper = "*"
rustc-serialize = "*"
